```python
a = (1, 2, [3, 4])
a[2] += [5, 6]

# 以上在 python 3.6.5 中抛出了 TypeError, 但 a[2] 的值还是变成了 [3, 4, 5, 6]
# 这是因为 a[2] 在增量时是分成两步
# 一是把 a[2] 的列表值入栈, 扩展成 [3, 4, 5, 6], 这是成功的
# 二是赋值回给元组元素 a[2], 这一步就出现的 TypeError
```

* 不要把可变对象放在元组中
* 列表增量赋值不是一个原子, 是分成两步进行的, 其实也可以从 list 没有实现 `__iadd__()` 可以看出. 因为自增会调用该方法, 如果没有实现该方法, 便才会调用 `__add__()` , 然后把结果赋值给原对象
* 可以通过 `dis.dis` 来查看 python 的字节码

